version: "3.9"

services:
  db:
    image: postgres:14-alpine
    container_name: viki-db
    environment:
      POSTGRES_USER: viki
      POSTGRES_PASSWORD: viki-secret
      POSTGRES_DB: viki
      TZ: Europe/Berlin
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  collector:
    build: .
    container_name: data-collector
    restart: unless-stopped
    environment:
      HOST: 192.168.1.42
      DB_URI: postgresql+psycopg2://ha:secret@db:5432/energy
    depends_on:
      - db

  backend:
    build:
      context: ./function/backend
      dockerfile: Dockerfile
    container_name: viki-backend
    depends_on:
      - db
    volumes:
      - ./function/backend:/app
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=dev-secret
      - JWT_SECRET_KEY=super-secret
      - MASTER_RESET_KEY=viki-masterkey
      - DATABASE_URL=postgresql://viki:viki-secret@db:5432/viki
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: function/nginx/Dockerfile
    container_name: viki-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: viki-certbot
    volumes:
      - ./function/nginx/certbot/www:/var/www/certbot
      - ./function/nginx/certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email you@example.com --agree-tos --no-eff-email
      -d controller.local"

volumes:
  db-data:
    external: true
    name: db-data
  db-statistic-data:
    external: true
    name: db-statistic
