services:
  db-data:
    image: postgres:14-alpine
    container_name: viki-data
    environment:
      POSTGRES_USER: viki
      POSTGRES_PASSWORD: viki-secret
      POSTGRES_DB: viki
      TZ: Europe/Berlin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      custom_net:
        ipv4_address: 172.20.0.2
    ports:
      - "5432:5432"
    restart: unless-stopped

  db-collector:
    image: viki-heat_db-collector:latest
    build:
      context: ./function/statistics
      dockerfile: Dockerfile
    container_name: data-statistic
    restart: unless-stopped
    environment:
      POSTGRES_USER: viki
      POSTGRES_PASSWORD: viki-secret
      POSTGRES_DB: viki_statistics
      TZ: Europe/Berlin
    volumes:
      - db-statistic-data:/var/lib/postgresql/data
    networks:
      custom_net:
        ipv4_address: 172.20.0.3
    ports:
      - "15433:5432"
    depends_on:
      - db-data

  backend:
    image: viki-heat_backend:latest
    build:
      context: ./function/backend
      dockerfile: Dockerfile
    container_name: viki-backend
    depends_on:
      - db-data
    volumes:
      - viki-log:/app/logs
    networks:
      custom_net:
        ipv4_address: 172.20.0.4
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=dev-secret
      - JWT_SECRET_KEY=super-secret
      - MASTER_RESET_KEY=viki-masterkey
      - DATABASE_URL=postgresql://viki:viki-secret@db:5432/viki
    restart: unless-stopped

  nginx:
    image: viki-heat_frontend:latest
    build:
      context: ./function/nginx
      dockerfile: Dockerfile
    container_name: viki-nginx
    networks:
      custom_net:
        ipv4_address: 172.20.0.5
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:
    name: db-data
  db-statistic-data:
    name: db-statistic
  viki-log:
    name: viki-log

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/29
